### ISSUE TITLE
CircleCI is only using PyQt5

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/qtpy#60]
I just noticed that we're only using PyQt5 to run our tests on CircleCI. This is of course wrong and must be fixed ASAP.

@goanpeca, this one is for you ;-)

**Comment by goanpeca** [comment]
Circle ci limits to 4 boxes... so thats all we can test simultaneously. I just chose qt5 for now... we could remove repeated tests from travis so that the load of tests is handled by both more uniformly.

Still, circle ci is by far the fastest ci out of appveyor and travis, so one can immediately spot a problem after a minute at most.

**Comment by ccordoba12** [comment]
Can't we run tests sequentially per Python version? I mean:

* Python 2.7: PyQt5, PyQt4, PySide
* Python 3.4: PyQt5, PyQt4, PySide
* Python 3.5: PyQt5, PyQt4

That way we'd only be using  3 boxes but we'd test all combinations.

**Comment by goanpeca** [comment]
We could, but ci-helpers would have to be dropped, and the yaml file would stop being nice and concise :-|....

**Comment by ccordoba12** [comment]
I don't think so. Instead of having this chunk of bash in the yaml file:

https://github.com/spyder-ide/qtpy/blob/master/circle.yml#L22

we could create a proper bash script that would iterate between Python Qt binding versions.

**Comment by goanpeca** [comment]
I dont think is a good idea, cause that would add a burden, and you loose the ability to know what failed on what configuration at a glance...

**Comment by goanpeca** [comment]
@astrofrog just wondering, if you have given more consideration to CIRCLE-CI working with ci-helpers.

Any chance of providing move test environments in order to support sequential builds on circle ci?

something like:
```yaml
machine:
  environment:
    # Python versions to test (Maximum of 4 different versions for now)
    PY_VERSIONS: "2.7 3.4 3.5"
    # Used by test scripts
    PATH: "$HOME/miniconda/bin:$PATH"  # To avoid prepending this to the commands on circle-ci
    CONDA_TEST_ENVS: "qt4 qt5"
    CONDA_CHANNELS: "qttesting"
    CONDA_DEPENDENCIES: "pyqt pytest pytest-cov qt=4.* | pyqt pytest pytest-cov qt=5.*"
    PIP_DEPENDENCIES: "coveralls"

...
```
